### PR TITLE
Fix MPU and BME power loss issue

### LINKED ISSUE #54: Fix bme
- Add a check for detecting chip and addr of bme, 
- check power loss issue breaking program
- add calibration
-  read pressure from config file

### PR DESCRIPTION
**Pull request by Mandeson**
Added re-initialization in case of sensor power loss.
When sensors are inoperational, return data is zero'ed

### CODE REVIEW

File: boards/src/bmp.cpp [hunk 1]
```diff
@@ -42,15 +42,28 @@ void init() {
...
+    vTaskDelay(pdMS_TO_TICKS(500));
+    float temperature = bmp_obj.readTemperature();
+    float pressure = bmp_obj.readPressure();
+    if (pressure < 0) { // if garbage data
+      data = Data{};
+      continue;
+    }
+    
+    // default values -> no measurement taken -> posible recent power loss -> the sensor is not initialized. We need to reinitialize it
+    if (fabs(temperature - 24.1500) < 0.001
```
Comment (Bartosz-Slowik) [inline boards/src/bmp.cpp]: to const

**Review by Bartosz-Slowik — CHANGES_REQUESTED** [review]

**Review by Bartosz-Slowik — APPROVED** [review]
lgtm
